version: "2"
services:
  web:
    build: .
    image: ctfhub/base_web_supervisor_python_36
    ports:
      - "8085:80"
    environment:
      - FLAG=ctfhub{supervisor_web}
      - MODULE_NAME=app
      - VARIABLE_NAME=app
      - WORK_CLASS=gevent
